### ISSUE TITLE
Saving a query / reusing it as function parameter

### ISSUE THREAD

**Issue by pherrymason** [ten3roberts/flax#11]
In documentation it is described that queries are cached, so if I reuse them I can get performance improvements.

Due to my lack of knowledge of rust, I'm getting some problems defining the query type in my structure, or even in function definitions.
Example:

I'm trying to pass a query to a function, so I can reuse same logic but for different cameras:

```
fn subsystem_render_items(query: &mut Query, world: &mut World, camera: Camera)
{
    for (id, sprite, transform, name) in &mut query.borrow(world) {
        // Do my stuff
    }
}

// So I can do from somewhere else...
pub fn system_render_item(game_state:GameState) {
    let mut query = Query::new((entity_ids(), sprite(), transform(), name()));
    let camera01 = Camera::new();
    subsystem_render_item(&mut query, game_state.world(), camera);
    
    
    let mut query = Query::new((entity_ids(), sprite(), transform(), name(), on_modal()));
    let camera01 = Camera::newModal();
    subsystem_render_item(&mut query, game_state.world(), camera);
}
```

The compiler complains the Query definition in my function signature is not correct, so I added as suggested:

```
fn subsystem_render_items<Q,F>(query: &mut Query<Q,F>, world: &mut World, camera: Camera)
    where
        Q: for<'x> Fetch<'x>,
        F: for<'x> Fetch<'x>,
```

But then, it's complaining because of the components I try to retrieve in the loop:

```
error[E0308]: mismatched types
  --> systems_draw.rs:79:9
   |
79 |     for (id, sprite, transform, name, ) in &mut query.borrow(world) {
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^    ------------------------ this is an iterator with items of type `<Q as FetchItem<'_>>::Item`
   ```
   
 I'm aware this is maybe more of a Rust question itself. Feel free to direct me away

**Comment by ten3roberts** [comment]
That is correct. The query itself remembers which archetypes to loop through, as well as changes since the last iteration if you are using e.g `.modified()`.

The query is generic over the fetch (and filter) to use and therefore which items are yielded.

Supplying the `Q: for<'x> Fetch<'x>` only constrains the query to be borrowed, but does not specify which items it will return, I.e; any query over any thing can do.

What I do is additionally constrain the item `Q` with `for<'x> Fetch<'x> + for<'y> FetchItem<'y, Item = ...>>`

Though going the fully generic route is rather verbose.

What I do instead is make the function take an `impl Iterator<Item = ...>` and then I do

`subsystem_render_item(query.borrow(&world).iter(), world, camera)`

Which is usually a lot easier if the function only needs to loop through the results.

**Comment by pherrymason** [comment]
Thanks for your response
