### ISSUE TITLE
How can I make relations_like mutable?

### ISSUE THREAD

**Issue by nikitabel229** [ten3roberts/flax#22]
I have this thingy, I want the `&f32` to be `&mut f32`. I thought that since relations are like components you could just do `as_mut`, but there's no `as_mut` here
![image](https://github.com/ten3roberts/flax/assets/50596758/6dbe6948-02c7-4d1c-960f-a59431a5c0c7)

**Comment by ten3roberts** [comment]
Yes, that is correct, relations are normal components but require the target to be specified `relationship(my_entity)` so that we know which piece of data we are talking about since there can be multiple ones.

As for the wildcard `relations_like` mutable access, I've added it in #23 , and will push a new version shortly, there's a new test for it too which would give you about what you want for usage

**Comment by nikitabel229** [comment]
Yay it works now, thanks 
![image](https://github.com/ten3roberts/flax/assets/50596758/09b83425-9e06-4652-b8bb-b3cc82e210ad)
